### ISSUE TITLE
Not work on Android P

### ISSUE THREAD

**Issue by taojiujiu** [hello2mao/XLogging#7]
When using this library on Android P 
Will throw Error:
```
    Process: com.hello2mao.xlogging.sample, PID: 24472
    java.lang.IllegalAccessError: Illegal class access: 'com.hello2mao.xlogging.internal.ssl.MonitoredSSLSocketFactory' attempting to access 'com.android.org.conscrypt.SSLParametersImpl' (declaration of 'com.hello2mao.xlogging.internal.ssl.MonitoredSSLSocketFactory' appears in /data/app/com.hello2mao.xlogging.sample-G6jifrwGvPzfnBKaSCzP9g==/split_lib_slice_6_apk.apk)
        at com.hello2mao.xlogging.internal.ssl.MonitoredSSLSocketFactory.getParameters(MonitoredSSLSocketFactory.java:30)
        at com.hello2mao.xlogging.internal.ssl.MonitoredSSLSocketFactory.<init>(MonitoredSSLSocketFactory.java:23)
        at com.hello2mao.xlogging.internal.ssl.Ssl.install(Ssl.java:21)
        at com.hello2mao.xlogging.XLogging.install(XLogging.java:49)
        at com.hello2mao.xlogging.sample.MainActivity.onClick(MainActivity.java:76)
        at com.hello2mao.xlogging.sample.MainActivity_ViewBinding$2.doClick(MainActivity_ViewBinding.java:49)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by hello2mao** [comment]
> When using this library on Android P
> Will throw Error:
> 
> ```
>     Process: com.hello2mao.xlogging.sample, PID: 24472
>     java.lang.IllegalAccessError: Illegal class access: 'com.hello2mao.xlogging.internal.ssl.MonitoredSSLSocketFactory' attempting to access 'com.android.org.conscrypt.SSLParametersImpl' (declaration of 'com.hello2mao.xlogging.internal.ssl.MonitoredSSLSocketFactory' appears in /data/app/com.hello2mao.xlogging.sample-G6jifrwGvPzfnBKaSCzP9g==/split_lib_slice_6_apk.apk)
>         at com.hello2mao.xlogging.internal.ssl.MonitoredSSLSocketFactory.getParameters(MonitoredSSLSocketFactory.java:30)
>         at com.hello2mao.xlogging.internal.ssl.MonitoredSSLSocketFactory.<init>(MonitoredSSLSocketFactory.java:23)
>         at com.hello2mao.xlogging.internal.ssl.Ssl.install(Ssl.java:21)
>         at com.hello2mao.xlogging.XLogging.install(XLogging.java:49)
>         at com.hello2mao.xlogging.sample.MainActivity.onClick(MainActivity.java:76)
>         at com.hello2mao.xlogging.sample.MainActivity_ViewBinding$2.doClick(MainActivity_ViewBinding.java:49)
>         at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
>         at android.view.View.performClick(View.java:6597)
>         at android.view.View.performClickInternal(View.java:6574)
>         at android.view.View.access$3100(View.java:778)
>         at android.view.View$PerformClick.run(View.java:25885)
>         at android.os.Handler.handleCallback(Handler.java:873)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.app.ActivityThread.main(ActivityThread.java:6669)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> ```

Sorry，目前已经不做这方面的工作，对于Android P的支持可能需要你们自己去适配。从报错看可能与Android P的SSL库已经做了加固有关。

**Comment by zhangqihui** [comment]
> When using this library on Android P
> Will throw Error:
> 
> ```
>     Process: com.hello2mao.xlogging.sample, PID: 24472
>     java.lang.IllegalAccessError: Illegal class access: 'com.hello2mao.xlogging.internal.ssl.MonitoredSSLSocketFactory' attempting to access 'com.android.org.conscrypt.SSLParametersImpl' (declaration of 'com.hello2mao.xlogging.internal.ssl.MonitoredSSLSocketFactory' appears in /data/app/com.hello2mao.xlogging.sample-G6jifrwGvPzfnBKaSCzP9g==/split_lib_slice_6_apk.apk)
>         at com.hello2mao.xlogging.internal.ssl.MonitoredSSLSocketFactory.getParameters(MonitoredSSLSocketFactory.java:30)
>         at com.hello2mao.xlogging.internal.ssl.MonitoredSSLSocketFactory.<init>(MonitoredSSLSocketFactory.java:23)
>         at com.hello2mao.xlogging.internal.ssl.Ssl.install(Ssl.java:21)
>         at com.hello2mao.xlogging.XLogging.install(XLogging.java:49)
>         at com.hello2mao.xlogging.sample.MainActivity.onClick(MainActivity.java:76)
>         at com.hello2mao.xlogging.sample.MainActivity_ViewBinding$2.doClick(MainActivity_ViewBinding.java:49)
>         at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
>         at android.view.View.performClick(View.java:6597)
>         at android.view.View.performClickInternal(View.java:6574)
>         at android.view.View.access$3100(View.java:778)
>         at android.view.View$PerformClick.run(View.java:25885)
>         at android.os.Handler.handleCallback(Handler.java:873)
>         at android.os.Handler.dispatchMessage(Handler.java:99)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.app.ActivityThread.main(ActivityThread.java:6669)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> ```

Have you solved this problem? How to solve it?
